# Generated by Django 3.2.15 on 2022-09-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assignees',
        ),
    ]
